      - name: Clone ONIE source
        run: |
          git clone --depth=1 --branch master https://github.com/opencomputeproject/onie.git
          ls -l onie/build-config/Makefile

      - name: Build ONIE for QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0
