name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl unzip python3 python3-pip \
            g++ libssl-dev autoconf automake libtool pkg-config \
            bison flex asciidoc u-boot-tools python3-apt \
            python3.10-venv

      - name: Clone ONIE repo
        run: |
          git clone --recursive https://github.com/opencomputeproject/onie.git

      - name: Build ONIE for QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0 V=1

      - name: List build output
        run: |
          ls -lh onie/build/images/x86_64-juniper_qfx5200-r0 || true
          ls -lh onie/build/x86_64-juniper_qfx5200-r0 || true

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: onie-qfx5200-output
          path: |
            onie/build/images/x86_64-juniper_qfx5200-r0/*
            onie/build/x86_64-juniper_qfx5200-r0/*
