name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ONIE source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl wget unzip git g++ make gcc \
            libtool-bin pkg-config gawk libncurses5-dev \
            python3 python3-pip python3-distutils python-is-python3 \
            bison flex xz-utils rsync texinfo

      - name: Set environment variables
        run: |
          echo "MACHINE=juniper_qfx5200" >> $GITHUB_ENV
          echo "MACHINEROOT=build-config/machine/juniper" >> $GITHUB_ENV

      - name: Prepare build folders
        run: |
          ls -lah
          ls -lah build-config/machine/juniper

      - name: Start build
        run: |
          make -j$(nproc) MACHINEROOT=${{ env.MACHINEROOT }} MACHINE=${{ env.MACHINE }} all

      - name: List build outputs
        run: |
          echo "Showing outputs under onie/build ..."
          find onie/build -type f | grep -i 'qfx\|onie\|.bin\|.iso' || echo "No output files found."

      - name: Upload ONIE Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: onie-artifacts
          path: |
            onie/build/images/x86_64-juniper_qfx5200-r0/**
            onie/build/x86_64-juniper_qfx5200-r0/**
          if-no-files-found: warn
