name: Build ONIE for QFX5200 (Diagnostic)

on:
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential git curl unzip python3 gawk libssl-dev bc xz-utils
      - name: Clone ONIE
        run: git clone --recursive https://github.com/opencomputeproject/onie.git && cd onie && git submodule update --init --recursive
      - name: Show directory structure
        run: |
          tree -L 2 onie
      - name: Attempt build
        run: |
          cd onie
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0 V=1
      - name: Show build artifacts
        run: |
          tree -L 3 onie/build
