name: Build and Publish ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git curl unzip python3 python3-pip gawk libssl-dev bc

      - name: Clone ONIE source
        run: |
          git clone --depth=1 https://github.com/opencomputeproject/onie.git
          ls -l onie/build-config/Makefile

      - name: Build ONIE for QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0

      - name: Prepare output for GitHub Pages
        run: |
          mkdir -p public
          cp onie/build/x86_64-juniper_qfx5200-r0/onie-installer-*.bin public/

      - name: Create download page
        run: |
          FILE=$(ls public/onie-installer-*.bin | xargs -n1 basename)
          echo "<html><body><h1>ONIE Installer for QFX5200</h1>" > public/index.html
          echo "<p><a href='$FILE' download>Download ONIE Installer</a></p>" >> public/index.html
          echo "<p>Direct link: <code>https://paa-fiap.github.io/onie/$FILE</code></p>" >> public/index.html
          echo "</body></html>" >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
