name: Build and Publish ONIE QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git curl unzip gawk python3 parted bc \
            binutils bison flex libssl-dev libelf-dev u-boot-tools \
            libncurses5-dev libncursesw5-dev autoconf automake \
            texinfo help2man libtool pkg-config

      - name: Clone ONIE source
        run: |
          git clone --depth=1 https://github.com/opencomputeproject/onie.git

      - name: Build ONIE for QFX5200
        run: |
          cd onie
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0

      - name: Generate SHA256SUMS
        run: |
          cd onie/build/x86_64-juniper_qfx5200-r0
          sha256sum * > SHA256SUMS

      - name: Move files to public for Pages
        run: |
          mkdir -p public/onie/x86_64-juniper_qfx5200-r0
          cp -v onie/build/x86_64-juniper_qfx5200-r0/* public/onie/x86_64-juniper_qfx5200-r0/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
