name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ONIE source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            g++ \
            make \
            python3 \
            unzip \
            wget \
            curl \
            git \
            libncurses5-dev \
            libssl-dev \
            bc \
            xz-utils \
            bison \
            flex \
            libelf-dev \
            u-boot-tools \
            fakeroot \
            cpio \
            rsync \
            gawk

      - name: Build ONIE for QFX5200
        working-directory: build-config
        run: |
          make -j$(nproc) MACHINEROOT=../machine/juniper MACHINE=juniper_qfx5200 all

      - name: List final image files
        run: |
          find build-config/build -type f | grep -i 'qfx\|onie\|.bin\|.iso' || echo "No output files found."

      - name: Upload ONIE Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: onie-artifacts
          path: |
            build-config/build/images/x86_64-juniper_qfx5200-r0/**
            build-config/build/x86_64-juniper_qfx5200-r0/**
          if-no-files-found: warn
