name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository (optional)
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl unzip git python3 python3-pip \
            g++ libssl-dev autoconf automake libtool pkg-config \
            bison flex asciidoc u-boot-tools \
            python3-venv python3-distutils

      - name: Clone ONIE source
        run: |
          git clone --recursive https://github.com/opencomputeproject/onie.git
          cd onie
          git submodule update --init --recursive
          ls -l build-config/Makefile

      - name: Build ONIE for Juniper QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0

      - name: List Build Output
        run: |
          ls -lh onie/build/images/x86_64-juniper_qfx5200-r0 || true
          ls -lh onie/build/x86_64-juniper_qfx5200-r0 || true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onie-qfx5200-artifacts
          path: |
            onie/build/images/x86_64-juniper_qfx5200-r0/*.bin
            onie/build/images/x86_64-juniper_qfx5200-r0/*.tar.gz
            onie/build/images/x86_64-juniper_qfx5200-r0/*.iso
          if-no-files-found: warn
