name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git curl unzip gawk \
            build-essential libtool \
            autoconf automake \
            texinfo pkg-config \
            python3 libncurses5-dev \
            bc zlib1g-dev

      - name: Clone ONIE repo (fixed commit with toolchain configs)
        run: |
          git clone https://github.com/opencomputeproject/onie.git
          cd onie
          git checkout e825b4a0d

      - name: Build ONIE for Juniper QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) MACHINEROOT=../machine/juniper MACHINE=juniper_qfx5200 all

      - name: Show available images
        run: |
          find onie/build -type f | grep -iE 'qfx|onie|\.bin|\.iso' || echo "No output files found."

      - name: Upload ONIE Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: onie-artifacts
          path: |
            onie/build/images/x86_64-juniper_qfx5200-r0/**
            onie/build/x86_64-juniper_qfx5200-r0/**
          if-no-files-found: warn
