name: Build ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-onie:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout ONIE source
        run: |
          git clone --recursive https://github.com/opencomputeproject/onie.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            wget \
            unzip \
            git \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-venv \
            python3-distutils \
            gawk \
            flex \
            bison \
            libssl-dev \
            bc \
            kmod \
            cpio \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            xz-utils \
            file \
            rsync \
            ccache \
            u-boot-tools \
            zlib1g-dev

      - name: Build ONIE for Juniper QFX5200
        run: |
          cd onie/build-config
          make -j$(nproc) MACHINE=juniper_qfx5200

      - name: List build output
        run: |
          ls -lh onie/build/images/x86_64-juniper_qfx5200-r0 || true
          ls -lh onie/build/x86_64-juniper_qfx5200-r0 || true
