name: Build and Publish ONIE for QFX5200

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git curl unzip python3 python3-pip gawk libssl-dev bc xz-utils

      - name: Clone ONIE source
        run: |
          git clone https://github.com/opencomputeproject/onie.git
          cd onie
          git submodule update --init --recursive

      - name: Build ONIE for QFX5200
        run: |
          cd onie
          make -j$(nproc) PLATFORM=x86_64-juniper_qfx5200-r0

      - name: List built image files
        run: |
          ls -lh onie/build/x86_64-juniper_qfx5200-r0/

      - name: Copy ONIE installer to public dir
        run: |
          mkdir -p public
          cp onie/build/x86_64-juniper_qfx5200-r0/onie-installer-x86_64-juniper_qfx5200-r0.bin public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
